Add JWT authentication with security configuration
jv-feb24-team1/car-sharing-service pull request #5
Opened 2024-05-31 14:41 UTC by SkillfulDev

*  Add security filter chain
*  Add jackson config
*  Add jwt autenticaton classes
*  Add custom user details service
*  Add hibernate sql style 
*  Add role entity
*

2024-05-31 16:29 UTC, azzilian requested changes
lets add EV to expiration date for resources just in case to not forget later

2024-05-31 16:29 UTC, azzilian commented on src/main/resources/application.properties
> +jwt.expetarion.time = 50 000 000
Mb it should be Environment Variable as well

2024-05-31 17:16 UTC, HAIOVYI requested changes
GJ!

2024-05-31 17:16 UTC, HAIOVYI commented on src/main/java/online/carsharing/entity/Role.java
> +    }
```suggestion
    private RoleType type;

    @Override
    public String getAuthority() {
        return "ROLE_" + type.name();
    }
```

2024-05-31 17:16 UTC, HAIOVYI commented on src/main/java/online/carsharing/repository/user/RoleRepository.java
> +    Optional<Role> findByName(RoleName roleName);
```suggestion
    Optional<Role> findByName(RoleType roleType);
```

2024-05-31 17:16 UTC, HAIOVYI commented on src/main/java/online/carsharing/security/JwtUtil.java
> +            throw new JwtTokenValidException("Expired or invalid JWT token", e);
```suggestion
            return false;
```

2024-05-31 17:16 UTC, HAIOVYI commented on src/main/java/online/carsharing/security/impl/AuthenticationServiceImpl.java
> +                new NoSuchElementException("Role CUSTOMER not found"));
`@PostConstruct
`

2024-05-31 17:46 UTC, azzilian submitted a review, later dismissed
Gj! Aprrove!

2024-06-01 07:17 UTC, HAIOVYI approved these changes
Very good!

2024-06-01 07:27 UTC, azzilian approved these changes

2024-06-01 07:28 UTC, merged